server:
  context-path: /seller
  port: 8083

rpc.manager.url : http://localhost:8081/manager/
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cache:
    type: hazelcast

  activemq:
    broker-url: tcp://192.168.10.16:61616
    packages:
      trust-all: true
logging:
  level:
    com.googlecode.jsonrpc4j: debug
