spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?user=root&password=root&useUnicode=true&characterEncoding=utf-8

  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  activemq:
    broker-url: tcp://192.168.10.16:61616
  jms:
    pub-sub-domain: true


server:
  context-path: /manager
  port: 8081
